baseURL = "https://coaxito.com"
title = "Breno's Blog"
author = "Breno Santana"
copyright = "Copyright © Breno Santana de Souza"
email = "breno@coaxito.com"
languageCode = "pt-br"
defaultContentLanguage = "pt-br"
enableRobotsTXT = true

disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]
[permalinks]
  blog = "/:slug/"

[params]
  # Descrição curta para meta tags SEO e previews (Idealmente < 160 caracteres)
  description = "Blog pessoal do Breno Santana, onde ele escreve sobre música, tecnologia, internet, fotografia e outros tópicos pessoais."
  # Imagem padrão para Open Graph / Twitter Cards (usada quando a página não tem imagem específica)
  # Recomenda-se usar uma imagem 1200x630px.
  images = ["images/default-share.jpg"]
  title = "Breno's Blog"
